language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq check
    - wget -q -O /tmp/libsodium.deb http://download.dnscrypt.org/libsodium/releases/libsodium_0.3+fpm0_amd64.deb
    - sudo dpkg -i /tmp/libsodium.deb
env:
    - USE_LIBGLIB=no
    - USE_LIBGLIB=yes
before_script:
    - ./autogen.sh
    - sh -c 'if [ "$USE_LIBGLIB" = "yes" ]; then ./configure --with-libglib CFLAGS="-Werror"; fi'
    - sh -c 'if [ "$USE_LIBGLIB" = "no" ]; then ./configure --without-libglib CFLAGS="-Werror"; fi'
script: make check
compiler:
    - clang
    - gcc
