language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq check
    - pushd /tmp
    - wget http://download.dnscrypt.org/libsodium/releases/libsodium-0.4.2.tar.gz
    - tar xzf libsodium-0.4.2.tar.gz
    - pushd libsodium-0.4.2
    - ./configure
    - make
    - sudo make install
    - popd
    - popd
    - ldconfig
env:
    - USE_LIBGLIB=no
    - USE_LIBGLIB=yes
before_script:
    - ./autogen.sh
    - sh -c 'if [ "$USE_LIBGLIB" = "yes" ]; then ./configure --with-libglib CFLAGS="-Werror"; fi'
    - sh -c 'if [ "$USE_LIBGLIB" = "no" ]; then ./configure --without-libglib CFLAGS="-Werror"; fi'
script: make check
compiler:
    - clang
    - gcc
