language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq check
    - pushd /tmp
    - wget --no-check-certificate https://download.libsodium.org/libsodium/releases/libsodium-0.4.3.tar.gz
    - tar xzf libsodium-0.4.3.tar.gz
    - pushd libsodium-0.4.3
    - ./configure
    - make
    - sudo make install
    - popd
    - popd
    - sudo ldconfig
before_script:
    - ./autogen.sh
    - ./configure CFLAGS="-Werror"
script: make check
compiler:
    - clang
    - gcc
